query getTests{
  getTests{
    data {
      ABTestBeginning
      WorkspaceA
      WorkspaceB
      Winner
      ConversionA
      ConversionALast24Hours
      ConversionB
      ConversionBLast24Hours
      WorkspaceASessions
      WorkspaceBSessions
      WorkspaceASessionsLast24Hours
      WorkspaceBSessionsLast24Hours
      hours
      proportion
      type
    }
    status
  }
}
